
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'nonassocPRINTleftPLUSNEGINT PLUS ASSIGN PAREN_START PAREN_END NEG NAME NEW_LINE PRINT INPUTmodule : statement_liststatement_list : statement_list NEW_LINE statementstatement_list : statementstatement : statement : PRINT expressionstatement : NAME ASSIGN expressionstatement : expressionexpression : expression PLUS expressionexpression : NEG expressionexpression : INTexpression : NAMEexpression : PAREN_START expression PAREN_ENDexpression : INPUT PAREN_START PAREN_END'
    
_lr_action_items = {'NAME':([0,3,4,6,11,16,18,],[1,12,12,12,12,1,12,]),'INT':([0,3,4,6,11,16,18,],[2,2,2,2,2,2,2,]),'NEG':([0,3,4,6,11,16,18,],[3,3,3,3,3,3,3,]),'PAREN_START':([0,3,4,6,9,11,16,18,],[4,4,4,4,17,4,4,4,]),'PAREN_END':([2,12,13,14,17,20,22,23,],[-10,-11,-9,20,22,-12,-13,-8,]),'PLUS':([1,2,10,12,13,14,15,19,20,22,23,],[-11,-10,18,-11,-9,18,18,18,-12,-13,-8,]),'PRINT':([0,16,],[6,6,]),'INPUT':([0,3,4,6,11,16,18,],[9,9,9,9,9,9,9,]),'NEW_LINE':([0,1,2,7,8,10,12,13,15,16,19,20,21,22,23,],[-4,-11,-10,-3,16,-7,-11,-9,-5,-4,-6,-12,-2,-13,-8,]),'ASSIGN':([1,],[11,]),'$end':([0,1,2,5,7,8,10,12,13,15,16,19,20,21,22,23,],[-4,-11,-10,0,-3,-1,-7,-11,-9,-5,-4,-6,-12,-2,-13,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement_list':([0,],[8,]),'expression':([0,3,4,6,11,16,18,],[10,13,14,15,19,10,23,]),'statement':([0,16,],[7,21,]),'module':([0,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> module","S'",1,None,None,None),
  ('module -> statement_list','module',1,'p_module_module','parse.py',54),
  ('statement_list -> statement_list NEW_LINE statement','statement_list',3,'p_newline_statement','parse.py',61),
  ('statement_list -> statement','statement_list',1,'p_statement_list','parse.py',65),
  ('statement -> <empty>','statement',0,'p_empty_statement','parse.py',68),
  ('statement -> PRINT expression','statement',2,'p_print_statement','parse.py',70),
  ('statement -> NAME ASSIGN expression','statement',3,'p_assign_statement','parse.py',73),
  ('statement -> expression','statement',1,'p_disard_statement','parse.py',76),
  ('expression -> expression PLUS expression','expression',3,'p_plus_expression','parse.py',79),
  ('expression -> NEG expression','expression',2,'p_neg_expression','parse.py',82),
  ('expression -> INT','expression',1,'p_int_expression','parse.py',85),
  ('expression -> NAME','expression',1,'p_name_expression','parse.py',88),
  ('expression -> PAREN_START expression PAREN_END','expression',3,'p_paren_expression','parse.py',91),
  ('expression -> INPUT PAREN_START PAREN_END','expression',3,'p_input_expression','parse.py',94),
]
